export const SongTest = {
  kind: "youtube#videoListResponse",
  etag: "6MojxjdEZL_0KBJ0Vlr2v2w8UT4",
  items: [
    {
      kind: "youtube#video",
      etag: "dFE5VU9f_5OqxDvw1ePmhF-ZFsA",
      id: "yKNxeF4KMsY",
      snippet: {
        publishedAt: "2011-05-30T13:12:47Z",
        channelId: "UCDPM_n1atn2ijUwHd0NNRQw",
        title: "Coldplay - Yellow (Official Video)",
        description:
          "Coldplay - Yellow is taken from the debut album Parachutes released in 2000\n\nNewly restored 4K version of the video added 10 July 2020.\n\nSubscribe for more content from Coldplay:\nhttps://bit.ly/subscribecoldplay\n\nListen to the album Parachutes on YouTube here:\nhttps://www.youtube.com/playlist?list=OLAK5uy_m4lOn8HJoLfTETxg2d6QouxcQd3nM4Gf0\n\nSee more official videos from Coldplay here:\nhttps://www.youtube.com/playlist?list=PLsvoYlzBrLFAJd4hNQSHw1lYjDKeQB_iU\n\nFOLLOW COLDPLAY\nWebsite: http://www.coldplay.com \nInstagram: http://instagram.com/coldplay\nTwitter: https://twitter.com/coldplay\nFacebook: https://www.facebook.com/coldplay\nTiktok: https://www.tiktok.com/@coldplay\nSpotify: https://bit.ly/coldplayspotify\nTumblr: http://coldplay.tumblr.com/\nVK: https://vk.com/coldplay\n\n🌙☀️\n\nABOUT COLDPLAY\nSince forming at university in London, Coldplay have gone on to become one of the planet’s most popular acts, selling more than 100 million copies of their eight Number One albums, which have spawned a string of hits including Yellow, Clocks, Fix You, Paradise, Viva La Vida, A Sky Full Of Stars, Hymn For The Weekend, Adventure Of A Lifetime, Orphans and, most recently, Higher Power.\n\n#Coldplay #Yellow #Parachutes",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/yKNxeF4KMsY/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/yKNxeF4KMsY/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/yKNxeF4KMsY/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/yKNxeF4KMsY/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/yKNxeF4KMsY/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Coldplay",
        tags: [
          "Coldplay",
          "Yellow",
          "Parachutes",
          "Official Music video",
          "Coldplay 2000",
          "Coldplay debut album",
          "Alternative",
          "Indie",
          "Pop",
          "Rock",
          "Chris Martin",
          "Jonny Buckland",
          "Guy Berryman",
          "Will Champion",
          "Parlophone",
          "Cold play",
          "Colplay",
          "Codplay",
          "Yelow",
          "Look At The Stars Look How They Shine For You",
          "coldplay 1st album",
          "coldplay first album",
          "it was all yellow",
          "coldplay yellow",
          "yellow coldplay",
          "yellow tiktok",
          "my yellow",
          "here's my yellow",
          "yello",
          "coldplay beach video",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "Coldplay - Yellow (Official Video)",
          description:
            "Coldplay - Yellow is taken from the debut album Parachutes released in 2000\n\nNewly restored 4K version of the video added 10 July 2020.\n\nSubscribe for more content from Coldplay:\nhttps://bit.ly/subscribecoldplay\n\nListen to the album Parachutes on YouTube here:\nhttps://www.youtube.com/playlist?list=OLAK5uy_m4lOn8HJoLfTETxg2d6QouxcQd3nM4Gf0\n\nSee more official videos from Coldplay here:\nhttps://www.youtube.com/playlist?list=PLsvoYlzBrLFAJd4hNQSHw1lYjDKeQB_iU\n\nFOLLOW COLDPLAY\nWebsite: http://www.coldplay.com \nInstagram: http://instagram.com/coldplay\nTwitter: https://twitter.com/coldplay\nFacebook: https://www.facebook.com/coldplay\nTiktok: https://www.tiktok.com/@coldplay\nSpotify: https://bit.ly/coldplayspotify\nTumblr: http://coldplay.tumblr.com/\nVK: https://vk.com/coldplay\n\n🌙☀️\n\nABOUT COLDPLAY\nSince forming at university in London, Coldplay have gone on to become one of the planet’s most popular acts, selling more than 100 million copies of their eight Number One albums, which have spawned a string of hits including Yellow, Clocks, Fix You, Paradise, Viva La Vida, A Sky Full Of Stars, Hymn For The Weekend, Adventure Of A Lifetime, Orphans and, most recently, Higher Power.\n\n#Coldplay #Yellow #Parachutes",
        },
      },
      contentDetails: {
        duration: "PT4M33S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "689516548",
        likeCount: "3708564",
        favoriteCount: "0",
        commentCount: "106351",
      },
    },
  ],
  pageInfo: {
    totalResults: 1,
    resultsPerPage: 1,
  },
};
